# Generated by Django 5.1.5 on 2025-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisoryFactor',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for each record', primary_key=True, serialize=False)),
                ('asset_class', models.CharField(help_text='Name of the asset class (e.g., Interest Rate, Equity, Credit)', max_length=255)),
                ('supervisory_factor', models.DecimalField(decimal_places=5, help_text='Supervisory factor value (e.g., 0.005)', max_digits=10)),
                ('effective_date', models.DateField(help_text='The date when this supervisory factor becomes effective')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or regulatory notes', null=True)),
            ],
            options={
                'verbose_name': 'Supervisory Factor',
                'verbose_name_plural': 'Supervisory Factors',
                'db_table': 'supervisory_factors',
            },
        ),
    ]
