# Generated by Django 5.1.5 on 2025-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(help_text='Unique identifier for the trade', max_length=50, unique=True)),
                ('netting_set_id', models.CharField(help_text='Identifier for the netting set to which the trade belongs', max_length=50)),
                ('asset_class', models.CharField(help_text='Asset class of the trade (e.g., Interest Rate, Equity)', max_length=50)),
                ('notional', models.DecimalField(decimal_places=2, help_text='Notional value of the trade', max_digits=20)),
                ('mtm', models.DecimalField(decimal_places=2, help_text='Mark-to-market value of the trade', max_digits=20)),
                ('collateral', models.DecimalField(decimal_places=2, default=0.0, help_text='Collateral value associated with the trade', max_digits=20)),
                ('is_collateral_posted', models.BooleanField(default=False, help_text='Indicates if collateral has been posted')),
                ('currency', models.CharField(default='USD', help_text='Currency of the trade', max_length=10)),
                ('market_date', models.DateField(help_text='Date when the market value was recorded')),
                ('trade_date', models.DateField(help_text='Date when the trade was executed')),
                ('maturity_date', models.DateField(help_text='Maturity date of the trade')),
                ('trade_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Active', help_text='Status of the trade', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the trade record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the trade record was last updated')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
            },
        ),
    ]
