# Generated by Django 5.1.5 on 2025-01-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='counterparty_id',
            field=models.CharField(blank=True, help_text='Identifier for counterparty to which the trade belongs', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='collateral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Collateral value associated with the trade', max_digits=20, null=True),
        ),
    ]
